### ISSUE TITLE
Can't start DS Virtual Console

### ISSUE THREAD

**Issue by Knkaku** [Nightkingale/Wii-U-Time-Sync#2]
Hello!
I was using version 1.0.1 of this Wii U Time Sync and when I try to launch the DS Virtual Console it freezes at the game start screen.
I went back to the first release, 1.0.0, and checked, and this problem did not occur.
This issue seems to be a bug specific to the latest version.

**Comment by Nightkingale** [comment]
Hello, thanks for submitting this! I can replicate it with Fire Emblem: Shadow Dragon on the latest version. The changes I have made in version 1.0.1 have been relatively minor, just addressing some oversights. I wonder what exactly I did in the latest update that's causing it.

I can't narrow it down to one particular change in the update, because I'm receiving the hang regardless of which changes I comment out. I'm continuing to look into it though, as I find this pretty serious.

**Comment by Maschell** [comment]
Related to https://github.com/devkitPro/wut/pull/323.

This is caused by using WUPS with latest wut.
For now you should be able to avoid this by using wut 1.2.0

**Comment by Nightkingale** [comment]
Thank you, @Maschell! That explains it! I used an older version of wut to build version 1.0.0, and then updated before building version 1.0.1. I rebuilt the binary using wut 1.2.0, and Nintendo DS titles work again. I'm going to do a bit more testing, but if all is well, this should now be addressed.
