### ISSUE TITLE
Μiiverse clock is 1 hour behind

### ISSUE THREAD

**Issue by erikiorai** [Nightkingale/Wii-U-Time-Sync#21]
After installing the Wii U Time sync aroma plugin the Miiverse clock still is 1 hour behind the the real time that I can see in HOME Menu

**Comment by Nightkingale** [comment]
Hey there, thanks for bringing this up! As far as I know, this isn't an issue with Wii U Time Sync itself. Instead, it seems the time on the Miiverse clock is provided by Nintendo/Pretendo.

If you want proof of this, you can set an inaccurate offset within Wii U Time Sync, reboot the console, then load Miiverse/Juxtaposition. For me personally, my Miiverse clock is an hour ahead of the time actually set on the system.

I believe it might be related to the timezone setting attached to Pretendo accounts. The issue is mine is set to `America/New_York` for some reason, and the Miiverse time displayed does not match up to the actual time over there. Maybe it has to do with Daylight Savings, or something else entirely?

I honestly don't think this is something we can control on our end. Even though this isn't really within our scope, I'm going to leave this open for now. I'll do some research, and if I figure out anything, I'll update here.

**Comment by erikiorai** [comment]
my Prentendo timezone is set to my correct one Athens/Europe

**Comment by Nightkingale** [comment]
I had just reached out to a few Pretendo developers to confirm my suspicions. From what I learned, Miiverse and Juxtaposition use a certain endpoint to fetch the time that doesn't seem to be used much elsewhere (or maybe anywhere else for that matter). Wii U Time Sync sets the time locally, but these services don't take the local time into account.

On that note, back when Miiverse was still around and Nintendo ran it, [apparently the time shown could have been off regardless.](https://www.reddit.com/r/wiiu/comments/28gf78/comment/ciapb0m/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) The biggest reason seems to be that Nintendo has notably ignored Daylight Savings Time, not just on Wii U, but on a lot of their older consoles. We implement something to handle it locally (because we can control it on our end), but it's not an "official Nintendo thing." I think this is probably the reason for your discrepancy.

Since that's the case, I don't really think there would be anything we could do to fix it on Wii U Time Sync's end. That would ultimately be up to Nintendo or Pretendo, if they choose to look into it.
